### ISSUE TITLE
Simple use case doesn't work :(

### ISSUE THREAD

**Issue by tangrammer** [webpack/expose-loader#10]
Hi webpack guys, 
I'm struggling with this tool, I've just followed your basic instructions but no way to access window.libraryName

This is my file.js
```
var a="saludo";
console.log(a);
module.exports={"saludo":a};
```
This is my expose-loader call
```
require("expose?libraryName!./file.js");
```
And this is the result I get :

![screen shot 2015-03-16 at 17 19 40](https://cloud.githubusercontent.com/assets/731829/6670727/ac940232-cc00-11e4-88ad-ca713d50a432.png)

Thanks in advance!
Juan

**Comment by tangrammer** [comment]
After a bit of more team working on that, We came upon that in webpack development mode your `window` isn't your `iframe.window`

**Comment by sokra** [comment]
yeah... better use the `--inline` mode of the webpack-dev-server. It's cooler and easier...

**Comment by framerate** [comment]
I think I'm having the same misunderstanding here...

```
require('expose?React!react');
```

just gives me

```
Error: Cannot find module 'expose?React!react'
```

so I think a step is missing from the tutorial readme? (or its late and I missed it)

**Comment by sokra** [comment]
> `Error: Cannot find module 'expose?React!react'`

**Comment by framerate** [comment]
This is in my `webpack.config.js file.`

Is that not meant how to do it? I was unclear based on the README. 

My goal was just to get React dom tools to work again.

**Comment by levithomason** [comment]
Lost here as well.  I've tried both the require and config approaches to no avail.  Double checked the docs on loaders but can't seem to get anything exposed to the window in either case.
