### ISSUE TITLE
Multiple Expose?

### ISSUE THREAD

**Issue by geminiyellow** [webpack/expose-loader#11]
e.g.

in webpack 's config file, how to expose jquery as jQuery and $?
have to write tow loader?

**Comment by pribilinskiy** [comment]
A glimpse on the code reveals that it is possible to expose multiple variables only by writing `expose` multiple times, e.g: `expose?$!expose?jQuery`

**Comment by shama** [comment]
Another way is just do `var jQuery = $ = require('jquery')` or `window.jQuery = window.$ = require('jquery')` to expose globally, as jQuery not supports this.

Thanks @pribilinskiy for a solution as well!
