### ISSUE TITLE
jQuery and moment work unless explicitly set to window in entry.js

### ISSUE THREAD

**Issue by simkessy** [webpack/expose-loader#13]
I get 
>Uncaught ReferenceError: jQuery is not defined

If I do: 
```
require("expose?$!jquery");
require('expose?moment!moment');
```
But when I write it out like this:

```
var $ = require('jquery');
window.jQuery = $;
window.$ = $;
var moment = require('moment');
window.moment = moment;
```

It seems to work fine. Is there a reason for this

**Comment by shama** [comment]
`require("expose?$!jquery");` only exposes the variable `$`. If you also want to expose the variable `jQuery` as well using this loader then do `expose?$!expose?jQuery`.

**Comment by simkessy** [comment]
I tried it  `require("expose?$!expose?jQuery");` and got this:

>ERROR in ./app/js/loader.js
Module not found: Error: Cannot resolve module 'expose' in C:\Users\Administrator\Dropbox\projects\spDash\app\js
 @ ./app/js/loader.js 1:0-33

**Comment by shama** [comment]
Oh sorry my mistake!

**Comment by simkessy** [comment]
No worries, put me on the right path. Thanks for the help.
